### ISSUE TITLE
Descrizione

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/nepero#1]
![es3_47](https://cloud.githubusercontent.com/assets/3002194/14767959/c91821dc-0a33-11e6-8be9-8236a58f04ac.png)

**Comment by FabioZTessitore** [comment]
Appena inizia il programma, Num vale 1, Conta vale Num-1=0, 1/0 fa infinito.

Cmq, mi spieghi che volevi fare?
Comincia a fare la parte a)

**Comment by FabioZTessitore** [comment]
ok, passiamo al punto b.
Devi scrivere un ciclo che somma tanti termini (quanti?) ognuno dei quali prevede il calcolo di un fattoriale.

**Comment by FabioZTessitore** [comment]
proviamo a mettere in pratica quanto hai scritto nel ragionamento (una g) solo che non devi usare una funzione

**Comment by lucifero55** [comment]
Scriverò sempre "funzione" per semplificare il concetto rendendo decisamente più comprensibile.

**Comment by lucifero55** [comment]
Come va?

**Comment by FabioZTessitore** [comment]
funziona.
d'ora in avanti cerca di usare nomi di variabili tali da rendere comprensibile il codice
